import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import SearchForm from "@/components/search/SearchForm";
import { Suspense } from "react";
// import { SearchContextProvider } from "@/components/search/SearchContextProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          defaultTheme="dark"
          enableSystem={false}
          attribute="class"
        >
            <Suspense>
              <div className="mt-2">
                <SearchForm />
              </div>
              <main className="mx-2 pt-6 lg:mx-[170px] md:mx-4 mb-8">
                {children}
              </main>
            </Suspense>
          
        </ThemeProvider>
      </body>
    </html>
  );
}
